// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test', async function() {
    await driver.get("https://bstackdemo.com/")
    await driver.manage().window().setRect({ width: 1050, height: 724 })
    await driver.findElement(By.css("#\\31 4 > .shelf-item__buy-btn")).click()
    await driver.findElement(By.id("signin")).click()
    await driver.findElement(By.css(".login_logo")).click()
    await driver.findElement(By.css(".css-1wa3eu0-placeholder")).click()
    await driver.findElement(By.id("react-select-3-input")).sendKeys("iker8avv")
    await driver.findElement(By.css(".w-80")).click()
    await driver.findElement(By.id("login-btn")).click()
    await driver.findElement(By.css(".login_wrapper")).click()
  })
})
